const PDFDocument = require("pdfkit");

const formatDate = (d) => {
  try {
    if (!d) return "";
    const date = new Date(d);
    if (Number.isNaN(date.getTime())) return "";
    return date.toISOString().slice(0, 10);
  } catch (_) {
    return "";
  }
};

module.exports = ({ res, order }) => {
  const fileName = `invoice-${order?.invoice || order?._id}.pdf`;

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=\"${fileName}\"`);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text("Invoice", { align: "right" });
  doc.moveDown(0.5);

  doc.fontSize(10).fillColor("#444");
  doc.text(`Invoice #: ${order?.invoice || "N/A"}`);
  doc.text(`Order ID: ${order?._id || "N/A"}`);
  doc.text(`Date: ${formatDate(order?.createdAt)}`);
  doc.moveDown();

  doc.fontSize(12).fillColor("#000").text("Customer", { underline: true });
  doc.moveDown(0.25);
  doc.fontSize(10).text(order?.name || "N/A");
  doc.fontSize(10).text(order?.email || "N/A");
  doc.fontSize(10).text(order?.contact || "N/A");
  doc.fontSize(10).text(`${order?.address || ""}`);
  doc.fontSize(10).text(`${order?.city || ""} ${order?.zipCode || ""}`.trim());
  doc.fontSize(10).text(`${order?.country || ""}`);
  doc.moveDown();

  doc.fontSize(12).fillColor("#000").text("Items", { underline: true });
  doc.moveDown(0.5);

  const tableTop = doc.y;
  const col1 = 50;
  const col2 = 90;
  const col3 = 320;
  const col4 = 400;
  const col5 = 470;

  doc.fontSize(10).fillColor("#000");
  doc.text("#", col1, tableTop);
  doc.text("Product", col2, tableTop);
  doc.text("Qty", col3, tableTop, { width: 60, align: "right" });
  doc.text("Price", col4, tableTop, { width: 60, align: "right" });
  doc.text("Amount", col5, tableTop, { width: 70, align: "right" });

  doc
    .moveTo(col1, tableTop + 15)
    .lineTo(545, tableTop + 15)
    .strokeColor("#ddd")
    .stroke();

  let y = tableTop + 25;
  const cart = Array.isArray(order?.cart) ? order.cart : [];

  cart.forEach((item, idx) => {
    const title = item?.title || "N/A";
    const qty = Number(item?.orderQuantity || 0);
    const price = Number(item?.price || 0);
    const amount = qty * price;

    doc.fillColor("#000");
    doc.text(String(idx + 1), col1, y);
    doc.text(title, col2, y, { width: 220 });
    doc.text(String(qty), col3, y, { width: 60, align: "right" });
    doc.text(price.toFixed(2), col4, y, { width: 60, align: "right" });
    doc.text(amount.toFixed(2), col5, y, { width: 70, align: "right" });

    y += 18;
    if (y > 720) {
      doc.addPage();
      y = 50;
    }
  });

  doc.moveDown();
  doc
    .moveTo(col1, y + 5)
    .lineTo(545, y + 5)
    .strokeColor("#ddd")
    .stroke();

  const shipping = Number(order?.shippingCost || 0);
  const discount = Number(order?.discount || 0);
  const total = Number(order?.totalAmount || 0);

  const totalsTop = y + 20;
  doc.fontSize(10).fillColor("#000");
  doc.text("Payment Method:", 330, totalsTop);
  doc.text(String(order?.paymentMethod || "N/A"), 450, totalsTop, {
    align: "right",
  });

  doc.text("Shipping:", 330, totalsTop + 16);
  doc.text(shipping.toFixed(2), 520, totalsTop + 16, { align: "right" });

  doc.text("Discount:", 330, totalsTop + 32);
  doc.text(discount.toFixed(2), 520, totalsTop + 32, { align: "right" });

  doc.fontSize(12).text("Total:", 330, totalsTop + 52);
  doc
    .fontSize(12)
    .text(total.toFixed(2), 520, totalsTop + 52, { align: "right" });

  doc.moveDown(2);
  doc
    .fontSize(9)
    .fillColor("#777")
    .text("Generated by the platform.", { align: "left" });

  doc.end();
};
